# Generated by Django 3.1.14 on 2022-10-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamID', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('max_members', models.IntegerField()),
            ],
        ),
    ]
