# Generated by Django 3.1.14 on 2022-10-19 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20221019_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='founder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='team.user'),
        ),
    ]
