# Generated by Django 3.1.14 on 2022-10-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20221019_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.CharField(choices=[('Information Technology', 'Information Technology'), ('Computer Science', 'Computer Science')], max_length=50, null=True),
        ),
    ]
