# Generated by Django 3.1.14 on 2022-10-19 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20221019_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='founder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='team.user'),
        ),
    ]
