# Generated by Django 3.1.14 on 2022-10-22 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20221019_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestTeam',
            fields=[
                ('requestTeamID', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('teamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.user')),
            ],
        ),
    ]
