# Generated by Django 3.1.14 on 2022-11-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_auto_20221026_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestteam',
            name='reason',
            field=models.TextField(null=True),
        ),
    ]
