# Generated by Django 4.1.3 on 2022-11-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_team_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
            ],
        ),
    ]
